package com.wbg.entity;

public class Authod {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authod.a_id
     *
     * @mbg.generated
     */
    private Integer aId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authod.a_name
     *
     * @mbg.generated
     */
    private String aName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authod.a_arrd
     *
     * @mbg.generated
     */
    private String aArrd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authod.a_sex
     *
     * @mbg.generated
     */
    private String aSex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authod.a_id
     *
     * @return the value of authod.a_id
     *
     * @mbg.generated
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authod.a_id
     *
     * @param aId the value for authod.a_id
     *
     * @mbg.generated
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authod.a_name
     *
     * @return the value of authod.a_name
     *
     * @mbg.generated
     */
    public String getaName() {
        return aName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authod.a_name
     *
     * @param aName the value for authod.a_name
     *
     * @mbg.generated
     */
    public void setaName(String aName) {
        this.aName = aName == null ? null : aName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authod.a_arrd
     *
     * @return the value of authod.a_arrd
     *
     * @mbg.generated
     */
    public String getaArrd() {
        return aArrd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authod.a_arrd
     *
     * @param aArrd the value for authod.a_arrd
     *
     * @mbg.generated
     */
    public void setaArrd(String aArrd) {
        this.aArrd = aArrd == null ? null : aArrd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authod.a_sex
     *
     * @return the value of authod.a_sex
     *
     * @mbg.generated
     */
    public String getaSex() {
        return aSex;
    }

    @Override
    public String toString() {
        return "Authod{" +
                "aId=" + aId +
                ", aName='" + aName + '\'' +
                ", aArrd='" + aArrd + '\'' +
                ", aSex='" + aSex + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authod.a_sex
     *
     * @param aSex the value for authod.a_sex
     *
     * @mbg.generated
     */
    public void setaSex(String aSex) {
        this.aSex = aSex == null ? null : aSex.trim();
    }
}