package com.wbg.entity;

import java.util.Date;

public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.p_id
     *
     * @mbg.generated
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.p_title
     *
     * @mbg.generated
     */
    private String pTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.p_date
     *
     * @mbg.generated
     */
    private Date pDate;

    @Override
    public String toString() {
        return "Post{" +
                "pId=" + pId +
                ", pTitle='" + pTitle + '\'' +
                ", pDate=" + pDate +
                ", pAuthod=" + pAuthod +
                ", authod=" + authod +
                ", pContext='" + pContext + '\'' +
                '}';
    }

    public Authod getAuthod() {
        return authod;
    }

    public void setAuthod(Authod authod) {
        this.authod = authod;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.p_authod
     *
     * @mbg.generated
     */
    private Integer pAuthod;
    private Authod authod;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.p_context
     *
     * @mbg.generated
     */
    private String pContext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.p_id
     *
     * @return the value of post.p_id
     *
     * @mbg.generated
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.p_id
     *
     * @param pId the value for post.p_id
     *
     * @mbg.generated
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.p_title
     *
     * @return the value of post.p_title
     *
     * @mbg.generated
     */
    public String getpTitle() {
        return pTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.p_title
     *
     * @param pTitle the value for post.p_title
     *
     * @mbg.generated
     */
    public void setpTitle(String pTitle) {
        this.pTitle = pTitle == null ? null : pTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.p_date
     *
     * @return the value of post.p_date
     *
     * @mbg.generated
     */
    public Date getpDate() {
        return pDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.p_date
     *
     * @param pDate the value for post.p_date
     *
     * @mbg.generated
     */
    public void setpDate(Date pDate) {
        this.pDate = pDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.p_authod
     *
     * @return the value of post.p_authod
     *
     * @mbg.generated
     */
    public Integer getpAuthod() {
        return pAuthod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.p_authod
     *
     * @param pAuthod the value for post.p_authod
     *
     * @mbg.generated
     */
    public void setpAuthod(Integer pAuthod) {
        this.pAuthod = pAuthod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.p_context
     *
     * @return the value of post.p_context
     *
     * @mbg.generated
     */
    public String getpContext() {
        return pContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.p_context
     *
     * @param pContext the value for post.p_context
     *
     * @mbg.generated
     */
    public void setpContext(String pContext) {
        this.pContext = pContext == null ? null : pContext.trim();
    }

}