package com.wbg.dao;

import com.wbg.entity.Authod;
import java.util.List;

public interface AuthodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authod
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authod
     *
     * @mbg.generated
     */
    int insert(Authod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authod
     *
     * @mbg.generated
     */
    Authod selectByPrimaryKey(Integer aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authod
     *
     * @mbg.generated
     */
    List<Authod> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authod
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Authod record);
}